language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - '7.3'
  - '7.4'

jobs:
  fast_finish: true

  include:
    # Minimum supported dependencies with the latest and oldest PHP version
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

    # Test supported LTS versions
    - php: 7.3
    - php: 7.4

    # Beta dependencies
    - php: 7.4
      env: STABILITY="dev"

  allow_failures:
    # Dev-master is allowed to fail.
    - env: STABILITY="dev"

before_install:
  - phpenv config-rm xdebug.ini || true
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --prefer-stable --no-interaction

script:
  - composer validate --strict --no-check-lock
  - ./vendor/bin/phpunit
