name: Static code analysis

on: [pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHP-CS-Fixer
        uses: docker://coverd/phpqa:latest
        with:
            args: php-cs-fixer fix --dry-run --diff-format udiff -vvv

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run PHPStan
        uses: docker://coverd/phpqa:latest
        with:
          args: phpstan analyze
